/**
 * Standard-library symbols the room autocompletes, per language.
 *
 * Deliberately **free of any CodeMirror import** — the CompletionSource that
 * consumes this lives in `editor-completions.ts`, and keeping them apart means
 * this data can be imported by tests or a future non-editor surface without
 * dragging the editor bundle in.
 *
 * Each entry can carry an `import` line. That is the whole auto-import feature:
 * accepting a completion whose library symbol is missing inserts both the usage
 * at the cursor *and* the required import at the top of the file, so a candidate
 * who types `System.out` gets `import java.lang.System;` for free instead of a
 * red error.
 */

export interface LanguageSymbol {
    /** Label shown in the completion list. */
    label: string;
    /** Text inserted when accepted. Defaults to `label`. */
    insert?: string;
    detail?: string;
    info?: string;
    type?: "keyword" | "function" | "method" | "class" | "variable" | "module";
    /** Line inserted at the top of the file, e.g. an import or #include. */
    import?: string;
    /** Skips the completion entirely once this text is found in the document. */
    importMarker?: string;
}

export const LANGUAGE_KEYWORDS: Record<string, LanguageSymbol[]> = {
    python: [
        { label: "def", type: "keyword" },
        { label: "class", type: "keyword" },
        { label: "return", type: "keyword" },
        { label: "if", type: "keyword" },
        { label: "elif", type: "keyword" },
        { label: "else", type: "keyword" },
        { label: "for", type: "keyword" },
        { label: "while", type: "keyword" },
        { label: "try", type: "keyword" },
        { label: "except", type: "keyword" },
        { label: "finally", type: "keyword" },
        { label: "with", type: "keyword" },
        { label: "lambda", type: "keyword" },
        { label: "yield", type: "keyword" },
        { label: "async", type: "keyword" },
        { label: "await", type: "keyword" },
        { label: "import", type: "keyword" },
        { label: "from", type: "keyword" },
        { label: "global", type: "keyword" },
        { label: "nonlocal", type: "keyword" },
        { label: "assert", type: "keyword" },
        { label: "del", type: "keyword" },
        { label: "pass", type: "keyword" },
        { label: "break", type: "keyword" },
        { label: "continue", type: "keyword" },
        { label: "not", type: "keyword" },
        { label: "and", type: "keyword" },
        { label: "or", type: "keyword" },
        { label: "in", type: "keyword" },
        { label: "is", type: "keyword" },
        { label: "None", type: "keyword" },
        { label: "True", type: "keyword" },
        { label: "False", type: "keyword" },
        { label: "self", type: "variable" },
        { label: "__name__", type: "variable" },
    ],
    javascript: [
        { label: "function", type: "keyword" },
        { label: "const", type: "keyword" },
        { label: "let", type: "keyword" },
        { label: "var", type: "keyword" },
        { label: "class", type: "keyword" },
        { label: "extends", type: "keyword" },
        { label: "return", type: "keyword" },
        { label: "if", type: "keyword" },
        { label: "else", type: "keyword" },
        { label: "for", type: "keyword" },
        { label: "for...of", insert: "for (const item of items) {\n\t$0\n}", type: "keyword" },
        { label: "while", type: "keyword" },
        { label: "switch", type: "keyword" },
        { label: "case", type: "keyword" },
        { label: "break", type: "keyword" },
        { label: "continue", type: "keyword" },
        { label: "try", type: "keyword" },
        { label: "catch", type: "keyword" },
        { label: "finally", type: "keyword" },
        { label: "throw", type: "keyword" },
        { label: "new", type: "keyword" },
        { label: "this", type: "keyword" },
        { label: "async", type: "keyword" },
        { label: "await", type: "keyword" },
        { label: "import", type: "keyword" },
        { label: "export", type: "keyword" },
        { label: "default", type: "keyword" },
        { label: "typeof", type: "keyword" },
        { label: "instanceof", type: "keyword" },
        { label: "null", type: "keyword" },
        { label: "undefined", type: "keyword" },
        { label: "true", type: "keyword" },
        { label: "false", type: "keyword" },
        { label: "Array.prototype.map", insert: "arr.map((item) => {\n\t$0\n})", detail: "snippet", type: "method" },
        { label: "Array.prototype.filter", insert: "arr.filter((item) => {\n\t$0\n})", detail: "snippet", type: "method" },
        { label: "for...in", insert: "for (const key in obj) {\n\t$0\n}", type: "keyword" },
    ],
    java: [
        { label: "public", type: "keyword" },
        { label: "private", type: "keyword" },
        { label: "protected", type: "keyword" },
        { label: "static", type: "keyword" },
        { label: "final", type: "keyword" },
        { label: "void", type: "keyword" },
        { label: "class", type: "keyword" },
        { label: "interface", type: "keyword" },
        { label: "extends", type: "keyword" },
        { label: "implements", type: "keyword" },
        { label: "new", type: "keyword" },
        { label: "return", type: "keyword" },
        { label: "if", type: "keyword" },
        { label: "else", type: "keyword" },
        { label: "for", type: "keyword" },
        { label: "forEach", insert: "forEach(item -> {\n\t$0\n});", type: "method" },
        { label: "while", type: "keyword" },
        { label: "switch", type: "keyword" },
        { label: "case", type: "keyword" },
        { label: "break", type: "keyword" },
        { label: "continue", type: "keyword" },
        { label: "try", type: "keyword" },
        { label: "catch", type: "keyword" },
        { label: "finally", type: "keyword" },
        { label: "throw", type: "keyword" },
        { label: "throws", type: "keyword" },
        { label: "this", type: "keyword" },
        { label: "super", type: "keyword" },
        { label: "null", type: "keyword" },
        { label: "true", type: "keyword" },
        { label: "false", type: "keyword" },
        { label: "int", type: "keyword" },
        { label: "long", type: "keyword" },
        { label: "double", type: "keyword" },
        { label: "char", type: "keyword" },
        { label: "boolean", type: "keyword" },
    ],
    cpp: [
        { label: "using", insert: "using namespace std;\n", type: "keyword" },
        { label: "namespace", type: "keyword" },
        { label: "template", type: "keyword" },
        { label: "typename", type: "keyword" },
        { label: "class", type: "keyword" },
        { label: "struct", type: "keyword" },
        { label: "public", type: "keyword" },
        { label: "private", type: "keyword" },
        { label: "protected", type: "keyword" },
        { label: "static", type: "keyword" },
        { label: "const", type: "keyword" },
        { label: "constexpr", type: "keyword" },
        { label: "auto", type: "keyword" },
        { label: "void", type: "keyword" },
        { label: "int", type: "keyword" },
        { label: "long", type: "keyword" },
        { label: "double", type: "keyword" },
        { label: "float", type: "keyword" },
        { label: "char", type: "keyword" },
        { label: "bool", type: "keyword" },
        { label: "return", type: "keyword" },
        { label: "if", type: "keyword" },
        { label: "else", type: "keyword" },
        { label: "for", insert: "for (int i = 0; i < n; ++i) {\n\t$0\n}", type: "keyword" },
        { label: "while", type: "keyword" },
        { label: "do", type: "keyword" },
        { label: "switch", type: "keyword" },
        { label: "case", type: "keyword" },
        { label: "break", type: "keyword" },
        { label: "continue", type: "keyword" },
        { label: "new", type: "keyword" },
        { label: "delete", type: "keyword" },
        { label: "try", type: "keyword" },
        { label: "catch", type: "keyword" },
        { label: "nullptr", type: "keyword" },
        { label: "true", type: "keyword" },
        { label: "false", type: "keyword" },
    ],
    go: [
        { label: "func", type: "keyword" },
        { label: "package", type: "keyword" },
        { label: "import", type: "keyword" },
        { label: "var", type: "keyword" },
        { label: "const", type: "keyword" },
        { label: "type", type: "keyword" },
        { label: "struct", insert: "type Name struct {\n\t$0\n}", type: "keyword" },
        { label: "interface", insert: "type Name interface {\n\t$0\n}", type: "keyword" },
        { label: "if", type: "keyword" },
        { label: "else", type: "keyword" },
        { label: "for", insert: "for i := 0; i < n; i++ {\n\t$0\n}", type: "keyword" },
        { label: "range", insert: "for key, value := range collection {\n\t$0\n}", type: "keyword" },
        { label: "switch", type: "keyword" },
        { label: "case", type: "keyword" },
        { label: "default", type: "keyword" },
        { label: "return", type: "keyword" },
        { label: "go", type: "keyword" },
        { label: "defer", type: "keyword" },
        { label: "chan", type: "keyword" },
        { label: "map", type: "keyword" },
        { label: "make", type: "keyword" },
        { label: "new", type: "keyword" },
        { label: "append", type: "function" },
        { label: "len", type: "function" },
        { label: "cap", type: "function" },
        { label: "nil", type: "keyword" },
        { label: "true", type: "keyword" },
        { label: "false", type: "keyword" },
    ],
};

/**
 * Library symbols that need an import.
 *
 * `importMarker` is what makes the feature idempotent: the import line is only
 * inserted when that exact text is absent from the document, so accepting the
 * same completion twice does not stack duplicate imports.
 */
export const LANGUAGE_LIBRARY: Record<string, LanguageSymbol[]> = {
    python: [
        { label: "sys", type: "module", import: "import sys", importMarker: "import sys" },
        { label: "os", type: "module", import: "import os", importMarker: "import os" },
        { label: "math", type: "module", import: "import math", importMarker: "import math" },
        { label: "random", type: "module", import: "import random", importMarker: "import random" },
        { label: "json", type: "module", import: "import json", importMarker: "import json" },
        { label: "collections", type: "module", import: "import collections", importMarker: "import collections" },
        { label: "datetime", type: "module", import: "from datetime import datetime", importMarker: "from datetime" },
        { label: "typing", type: "module", import: "from typing import List, Dict, Optional", importMarker: "from typing" },
        {
            label: "sys.stdout.write",
            insert: "sys.stdout.write(str($0))",
            type: "function",
            import: "import sys",
            importMarker: "import sys",
            info: "Writes to standard output without a trailing newline.",
        },
        { label: "print", insert: "print($0)", type: "function" },
        { label: "len", insert: "len($0)", type: "function" },
        { label: "range", insert: "range($0)", type: "function" },
        { label: "enumerate", insert: "enumerate($0)", type: "function" },
        { label: "zip", insert: "zip($0)", type: "function" },
        { label: "sorted", insert: "sorted($0)", type: "function" },
        { label: "sum", insert: "sum($0)", type: "function" },
        { label: "min", insert: "min($0)", type: "function" },
        { label: "max", insert: "max($0)", type: "function" },
        { label: "abs", insert: "abs($0)", type: "function" },
        { label: "int", insert: "int($0)", type: "function" },
        { label: "str", insert: "str($0)", type: "function" },
        { label: "float", insert: "float($0)", type: "function" },
        { label: "list", insert: "list($0)", type: "class" },
        { label: "dict", insert: "dict($0)", type: "class" },
        { label: "set", insert: "set($0)", type: "class" },
        { label: "tuple", insert: "tuple($0)", type: "class" },
        { label: "isinstance", insert: "isinstance($0)", type: "function" },
        { label: "map", insert: "map($0)", type: "class" },
        { label: "filter", insert: "filter($0)", type: "class" },
        { label: "reversed", insert: "reversed($0)", type: "function" },
    ],
    javascript: [
        { label: "console.log", insert: "console.log($0)", type: "method" },
        { label: "console.error", insert: "console.error($0)", type: "method" },
        { label: "console.table", insert: "console.table($0)", type: "method" },
        { label: "Math.max", insert: "Math.max($0)", type: "method" },
        { label: "Math.min", insert: "Math.min($0)", type: "method" },
        { label: "Math.floor", insert: "Math.floor($0)", type: "method" },
        { label: "Math.abs", insert: "Math.abs($0)", type: "method" },
        { label: "JSON.stringify", insert: "JSON.stringify($0)", type: "function" },
        { label: "JSON.parse", insert: "JSON.parse($0)", type: "function" },
        { label: "Object.keys", insert: "Object.keys($0)", type: "method" },
        { label: "Object.entries", insert: "Object.entries($0)", type: "method" },
        { label: "Object.values", insert: "Object.values($0)", type: "method" },
        { label: "Array.isArray", insert: "Array.isArray($0)", type: "function" },
        { label: "Number.isInteger", insert: "Number.isInteger($0)", type: "function" },
        { label: "parseInt", insert: "parseInt($0, 10)", type: "function" },
        { label: "parseFloat", insert: "parseFloat($0)", type: "function" },
        { label: "isNaN", insert: "isNaN($0)", type: "function" },
        { label: "setTimeout", insert: "setTimeout(() => {\n\t$0\n}, 0)", type: "function" },
        { label: "Promise", insert: "new Promise((resolve, reject) => {\n\t$0\n})", type: "class" },
    ],
    java: [
        {
            label: "System.out.println",
            insert: "System.out.println($0);",
            type: "method",
            info: "Prints a line to standard output.",
        },
        {
            label: "System.out.printf",
            insert: "System.out.printf($0);",
            type: "method",
        },
        {
            label: "System.err.println",
            insert: "System.err.println($0);",
            type: "method",
            info: "Prints a line to standard error.",
        },
        { label: "Scanner", insert: "new Scanner(System.in)", type: "class", import: "import java.util.Scanner;", importMarker: "java.util.Scanner" },
        { label: "ArrayList", insert: "new ArrayList<>()", type: "class", import: "import java.util.ArrayList;", importMarker: "java.util.ArrayList" },
        { label: "HashMap", insert: "new HashMap<>()", type: "class", import: "import java.util.HashMap;", importMarker: "java.util.HashMap" },
        { label: "HashSet", insert: "new HashSet<>()", type: "class", import: "import java.util.HashSet;", importMarker: "java.util.HashSet" },
        { label: "List", insert: "List<$0>", type: "class", import: "import java.util.List;", importMarker: "java.util.List" },
        { label: "Map", insert: "Map<$0>", type: "class", import: "import java.util.Map;", importMarker: "java.util.Map" },
        { label: "Arrays.sort", insert: "Arrays.sort($0)", type: "method", import: "import java.util.Arrays;", importMarker: "java.util.Arrays" },
        { label: "Collections.sort", insert: "Collections.sort($0)", type: "method", import: "import java.util.Collections;", importMarker: "java.util.Collections" },
        { label: "StringBuilder", insert: "new StringBuilder()", type: "class", import: "import java.lang.StringBuilder;", importMarker: "StringBuilder" },
        { label: "Math.max", insert: "Math.max($0)", type: "method" },
        { label: "Math.abs", insert: "Math.abs($0)", type: "method" },
        { label: "Integer.parseInt", insert: "Integer.parseInt($0)", type: "method" },
        { label: "String.valueOf", insert: "String.valueOf($0)", type: "method" },
        { label: "BufferedReader", insert: "new BufferedReader(new InputStreamReader(System.in))", type: "class", import: "import java.io.BufferedReader;", importMarker: "java.io.BufferedReader" },
    ],
    cpp: [
        {
            label: "cout",
            insert: "cout << $0",
            type: "variable",
            import: "#include <iostream>",
            importMarker: "#include <iostream>",
            info: "Standard output stream. Needs <iostream>.",
        },
        {
            label: "cin",
            insert: "cin >> $0",
            type: "variable",
            import: "#include <iostream>",
            importMarker: "#include <iostream>",
            info: "Standard input stream. Needs <iostream>.",
        },
        { label: "endl", insert: "endl", type: "variable" },
        { label: "vector", insert: "vector<$0>", type: "class", import: "#include <vector>", importMarker: "#include <vector>" },
        { label: "string", insert: "string", type: "class", import: "#include <string>", importMarker: "#include <string>" },
        { label: "sort", insert: "sort($0)", type: "function", import: "#include <algorithm>", importMarker: "#include <algorithm>" },
        { label: "reverse", insert: "reverse($0)", type: "function", import: "#include <algorithm>", importMarker: "#include <algorithm>" },
        { label: "map", insert: "map<$0>", type: "class", import: "#include <map>", importMarker: "#include <map>" },
        { label: "set", insert: "set<$0>", type: "class", import: "#include <set>", importMarker: "#include <set>" },
        { label: "queue", insert: "queue<$0>", type: "class", import: "#include <queue>", importMarker: "#include <queue>" },
        { label: "pair", insert: "pair<$0>", type: "class", import: "#include <utility>", importMarker: "#include <utility>" },
        { label: "INT_MAX", insert: "INT_MAX", type: "variable", import: "#include <climits>", importMarker: "#include <climits>" },
        { label: "accumulate", insert: "accumulate($0)", type: "function", import: "#include <numeric>", importMarker: "#include <numeric>" },
        { label: "make_unique", insert: "make_unique<$0>()", type: "function", import: "#include <memory>", importMarker: "#include <memory>" },
    ],
    go: [
        { label: "fmt.Println", insert: "fmt.Println($0)", type: "function", import: 'import "fmt"', importMarker: '"fmt"' },
        { label: "fmt.Printf", insert: "fmt.Printf($0)", type: "function", import: 'import "fmt"', importMarker: '"fmt"' },
        { label: "fmt.Sprintf", insert: "fmt.Sprintf($0)", type: "function", import: 'import "fmt"', importMarker: '"fmt"' },
        { label: "strings.Split", insert: "strings.Split($0, \" \")", type: "function", import: 'import "strings"', importMarker: '"strings"' },
        { label: "strings.Join", insert: "strings.Join($0)", type: "function", import: 'import "strings"', importMarker: '"strings"' },
        { label: "strings.ToUpper", insert: "strings.ToUpper($0)", type: "function", import: 'import "strings"', importMarker: '"strings"' },
        { label: "strings.Contains", insert: "strings.Contains($0)", type: "function", import: 'import "strings"', importMarker: '"strings"' },
        { label: "sort.Ints", insert: "sort.Ints($0)", type: "function", import: 'import "sort"', importMarker: '"sort"' },
        { label: "sort.Slice", insert: "sort.Slice($0)", type: "function", import: 'import "sort"', importMarker: '"sort"' },
        { label: "strconv.Atoi", insert: "strconv.Atoi($0)", type: "function", import: 'import "strconv"', importMarker: '"strconv"' },
        { label: "strconv.Itoa", insert: "strconv.Itoa($0)", type: "function", import: 'import "strconv"', importMarker: '"strconv"' },
        { label: "os.ReadFile", insert: "os.ReadFile($0)", type: "function", import: 'import "os"', importMarker: '"os"' },
        { label: "errors.New", insert: "errors.New($0)", type: "function", import: 'import "errors"', importMarker: '"errors"' },
        { label: "make", insert: "make($0)", type: "function" },
        { label: "len", insert: "len($0)", type: "function" },
        { label: "cap", insert: "cap($0)", type: "function" },
        { label: "copy", insert: "copy($0)", type: "function" },
        { label: "delete", insert: "delete($0)", type: "function" },
    ],
};

export const symbolsForLanguage = (language: string | null | undefined): LanguageSymbol[] =>
    (language && LANGUAGE_KEYWORDS[language]) || [];

export const libraryForLanguage = (language: string | null | undefined): LanguageSymbol[] =>
    (language && LANGUAGE_LIBRARY[language]) || [];
